### ISSUE TITLE
Reading from file causes AccessViolationException

### ISSUE THREAD

**Issue by neil-s** [jmp75/rdotnet#13]
When you try to `Evaluate` a line calling `read.csv`, the application crashes with an AccessViolationException. Copying the same command into RStudio and running it there correctly loads the file into a dataframe.

Code to reproduce, where `rawFileName` is a regular Windows path to a csv file.

     dataFileName = rawFileName.Replace(@"/", @"//"); 
     string loadDataCommand = String.Format(@"userData <- read.csv('{0}')", dataFileName);
     this.engine.Evaluate(loadDataCommand);

Running any other type of R code in the same place causes no errors, but any attempts to read a file cause the application to crash and complain about attempted access to restricted memory.

**Comment by skyguy94** [comment]
What version of R and R.Net are you using? I suspect that your R.Net may be out of date.

I used this 800mb csv file: http://spatialkeydocs.s3.amazonaws.com/FL_insurance_sample.csv.zip and this code to load the file:
```
using System;
using RDotNet;

namespace RDotNetTester
{
    internal class Program
    {
        private static void Main()
        {
            using (var engine = REngine.GetInstance())
            {
                const string dataFileName = "D:/Projects/RDotNetTester/test.csv";
                string loadDataCommand = String.Format(@"userData <- read.csv('{0}')", dataFileName);
                engine.Evaluate(loadDataCommand);
            }
        }
    }
}
```
and had no issues.

**Comment by neil-s** [comment]
Both were installed very recently. R.NET is at 1.5.21 from NuGet, the system R is at 3.1.3.

**Comment by neil-s** [comment]
Ah I fixed it! Just changed the first line to:
    dataFileName = rawFileName.Replace(@"\", @"//");
The Windows path had backslashes, which R can't seem to deal with. Normalizing them fixes the issue.

**Comment by skyguy94** [comment]
I get the exception now. FWIW, \x is an escape sequence and R does toss an error onto the console describing the issue.

This is the corrected version:
```
const string dataFileName = @"D:\\\\Projects\\RDotNetTester\\test.csv";
string loadDataCommand = String.Format(@"userData <- read.csv('{0}')", dataFileName);
engine.Evaluate(loadDataCommand);
```

The exception occurs during the call to `ParseVector`. Normally we would get a parse error, but from the console message it seems that `Rf_mkString` is failing due to the unrecognized escape sequence even though it returns what looks like a valid `SEXP`.

From Rengine.cs:668
```
            incompleteStatement.Append(statement);
            var s = GetFunction<Rf_mkString>()(incompleteStatement.ToString());
            string errorStatement;
            using (new ProtectedPointer(this, s))
            {
                ParseStatus status;
                var vector = new ExpressionVector(this, GetFunction<R_ParseVector>()(s, -1, out status, NilValue.DangerousGetHandle()));
```

`R_ParseVector` is the external entrypoint that does a little setup and calls `R_Parse` and `R_Parse` will return a status code enum value, so the access violation is curious. RStudio handles it without crashing and that's my usual model for correct behavior and bug/not a bug determinations. I poke around the RStudio source a bit to double check our handling.
