### ISSUE TITLE
R.Net and Docker?

### ISSUE THREAD

**Issue by KevinBurton** [jmp75/rdotnet#66]
I have an dotnet application running in one container and 'R' running in another. How do I set up the various environment variables to point to this 'R' container? Should the 'R' container be running interactive? Any tips on interacting with the 'R' container would be appreciated.

Thank you

**Comment by ChrisLincoln** [comment]
@KevinBurton Did you ever get a functioning environment using the architecture you described above? I have been toying with the idea of doing something similar, but my understanding of R.Net was that it is using "in-process" bindings (or out-of-process but tied to the same machine).  I have found other C# <-> R integration techniques that use IP, which would be a natural fit for containerization.  It has been a few months since I have done that research, so the names of the libraries are exactly fresh on my mind.

**Comment by KevinBurton** [comment]
@ChrisLincoln I have not brought up an environment yet but like you am leaning towards more API oriented approaches. It seems that R.NET is more "in-process" and approaches like [OpenCpu](https://www.opencpu.org/) are more what I am looking for. Keep me posted on what you find also.

**Comment by jmp75** [comment]
@KevinBurton indeed you are on the money, R.NET and R are in the same process, with direct P/Invoke interop. I cannot vouch for why this was so at R.NET inception, but it has the advantage of scalibility with data size (likely higher performance) compared to client/server ones. The main downside is with web apps, since IIS is multi-threading but R is not thread-safe.
