### ISSUE TITLE
unable to load shared object 'C:/Program Files/R/R-3.4.3/library/stats/libs/x64/stats.dll'

### ISSUE THREAD

**Issue by qwasal** [jmp75/rdotnet#71]
Using RDotNet 1.7.0 downloaded from NuGet
Compiling with VS2017 using .NET 4.6.1

Error: package or namespace load failed for 'stats' in inDL(x, as.logical(local), as.logical(now), ...):
 unable to load shared object 'C:/Program Files/R/R-3.4.3/library/stats/libs/x64/stats.dll':
  LoadLibrary failure:  The specified module could not be found.

Verified the dll exists at the target location.
Verified the project is being compiled in 64 bits.

Not sure what else to try.

**Comment by lrasmus** [comment]
I think this is the same as #62 , where it appears the R packagers accidentally included a file (etc/Renviron.site) in the 3.4.3 distribution, which is throwing things off.  More details in the linked issue, but if you delete etc/Renviron.site (from your R install directory), you should be all set.

**Comment by qwasal** [comment]
Ahh, sorry about that.  I looked right at #62 and it simply didn't click it applied.

Thank you.

**Comment by edmizac** [comment]
I was trying to run nrlx package in R (connection with R and NetLogo) while running the R-extension, and I have solved this problem of missing dll as below:

1) Changed R and RStudio installations to my admin user

2) Following @kevinushey in [this link](https://community.rstudio.com/t/unable-to-load-shared-object-on-startup-in-rstudio-only/33107/3) which called my attention to my empty Sys.which("stats.dll"), I added ALL the following paths to my PATH in Windows (but the last two seemed to make the difference):

C:\Program Files\R\R-4.2.1\bin\x64\;
C:\Program Files\R\R-4.2.1\bin\i386;
C:\PROGRA~1\R\R-42~1.1\bin\x64;
C:\Users\USER\AppData\Local\Programs\R\R-4.2.1\library\rJava\jri;
C:\Program Files\R\R-4.2.1\library\stats;
C:\Users\USER\AppData\Local\R\bin\x64;
C:\Users\USER\AppData\Local\R\library\stats\libs\x64

3) Deleted 'Rprofile.site' from the below folder following @lrasmus in [this issue](https://github.com/rdotnet/rdotnet/issues/62) 
C:\Users\user\AppData\Local\Programs\R\R-4.2.1\etc

I hope this helps.


PS: I see this issue is reported [other issues](https://github.com/rdotnet/rdotnet/issues/62)
