### ISSUE TITLE
integer creation and then coercion fails with R 3.5. 

### ISSUE THREAD

**Issue by jmp75** [jmp75/rdotnet#76]
R 3.5
Commit: 9a535ce04f6a7bbeea9ef4e3441e0eb1e4a823cc [9a535ce]
Date: Friday, 11 May 2018 9:50:44 PM
`public void TestCreateIntegerVectorValid()` fails
```C#
            engine.Evaluate("x <- 1:100");
            var vec = engine.GetSymbol("x").AsInteger();
```
checking on 'vec' values are very different from expected.

**Comment by jmp75** [comment]
Very odd because in R src code in `SEXP coerceVector(SEXP v, SEXPTYPE type)`  :
```C
    if (TYPEOF(v) == type)
	return v;
```

**Comment by lrasmus** [comment]
I traced through this a little more, and it does seem it's going through the branch you pointed out in the R code where it just returns the vector pointer (see my mental tracing below).

I think the issue is the way the vector is packed to begin with - it looks like it's using the ALTREP format.  Within the unit test, it's trying to convert the vector to a C# int[], which is calling GetArrayFast, which in turn is doing a direct memory copy starting from the DataPointer address.  Because this is packaged up as ALTREP, that won't work. 

```
engine.GetSymbol("x")
  Handle: 0x0000000020C845B8
  Type:   13  (Integer Vector)
  ALTREP: 1   (Alternative Representation)

  .AsInteger()
    Calls Rf_coerceVector.  Return:
      Handle: 0x0000000020C845B8   (Same as GetSymbol)
      Type:   13  (Integer Vector)
      ALTREP: 1   (Alternative Representation)
```

**Comment by lrasmus** [comment]
@jmp75 - I think I've got a handle on this now.  This is in that old branch (not based on the nice one you merged other changes for), but I'll work on that next.  I just wanted to get a gut check from you on this approach.  In this commit - https://github.com/StatTag/rdotnet/commit/d935049274d712ae3caa7aadf2689feeecfe0d8b

I have passing tests for sequential (which uses ALTREP) and non-sequential integer vectors.  The same type of approach will need to be applied to other vector types, if this looks good.

**Comment by jmp75** [comment]
@lrasmus - thank you; I think we can close this issue. Solved after merge as of:
Commit: dcb63def00a2e7efe13f1dba2132b818ff177661 [dcb63de]
Date: Saturday, 12 May 2018 9:25:46 AM
